apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: server-dep
spec:
  selector:
    matchLabels:
      app: server-dep
  replicas: 2
  template:
    metadata:
      labels:
        app: server-dep
    spec:
      containers:
      - name: server-dep
        image: tomeroz802/customer-app:server
        ports:
        - containerPort: 3001