apiVersion: v1
kind: Service
metadata:
  name: server-deployment
spec:
  type: NodePort
  selector:
    app: customer-app 
  ports:
    - name: http
      protocol: TCP
      nodePort: 32000
      targetPort: 3000
      port: 3000
  externalIPs:
    - 4.245.216.252
    