apiVersion: v1
kind: Service
metadata:
  name: server-deployment
spec:
  type: NodePort
  selector:
    app: server 
  ports:
    - name: http
      protocol: TCP
      nodePort: 32001
      targetPort: 3001
      port: 3001
  externalIPs:
    - 4.245.216.252
    