apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values.serviceserver.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deploymentserver.app }}
  ports:
    - name: http
      protocol: TCP
      nodePort: {{ .Values.serviceserver.nodePort }}
      targetPort: {{ .Values.serviceserver.targetPort }}
      port: {{ .Values.serviceserver.port }}
  externalIPs:
    - {{ .Values.serviceserver.externalIP }}
    