apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceclient.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deploymentclient.app }}
  ports:
    - name: http
      protocol: TCP
      nodePort: {{ .Values.serviceclient.nodePort }}
      targetPort: {{ .Values.serviceclient.targetPort }}
      port: {{ .Values.serviceclient.port }}
  externalIPs:
    - {{ .Values.serviceserver.externalIP }}
    